[package]
name = "mtk"
edition.workspace = true
version.workspace = true
authors.workspace = true

[dependencies]
bytemuck = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
parley = { workspace = true }
pollster = { workspace = true }
resvg = { workspace = true }
swash = { workspace = true }
wgpu = { workspace = true }
winit = { workspace = true }
zune-image = { workspace = true }
arboard = { workspace = true }
mtk-macro = { path = "../mtk-macro" }

[build-dependencies]
bindgen = "0.72.1"
cc = "1.2.66"
